on:
  push:
    # branches: [main]

name: Create Release

jobs:
  build:
    name: Create Rlease
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'

      - name: Build the project
        run: uv build

      - name: Create a Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          generate_release_notes: true
          files: ./dist/*
